### ISSUE TITLE
Logger Aborting with(#0) with Error

### ISSUE THREAD

**Issue by iUwej** [godaddy/Thespian#23] opened 2016-10-20 11:56 UTC
`ERROR:root:Thespian Logger aborting (#0) with error
Traceback (most recent call last):
  File "/home/soko/Env/soko_env/local/lib/python2.7/site-packages/thespian/system/logdirector.py", line 74, in startupASLogger
    logrecord = r.message
AttributeError: 'Thespian__UpdateWork' object has no attribute 'message'
INFO:Thespian.Admin:ActorSystem Administrator startup @ ActorAddr-Q.ThespianQ
'Thespian__UpdateWork' object has no attribute 'message'
`
I have a "multiprocQueueBase" actor system on my django app but the logger keep on aborting with the above error trace. Sending messages within the actor system is not working. Am I missing some configuration? How do I resolve the issue?

**Comment by kwquick** [comment] 2016-10-20 20:17
You should not need any special configuration.  This looks like a bug possibly related to the multiple threads in Django.  Thank your for the report, and I'm checking into this now...

**Comment by kwquick** [comment] 2016-10-20 20:24
This was an overlooked use case for a recent change.  I've pushed two patches, and https://github.com/godaddy/Thespian/commit/96fcf0dc9e9e40ee802dfe24bf0338e2c6d0dd31 in particular should address the problem.  

Please let me know if this fixes your problem and if so I will generate a release shortly with this fix.  If this does not fix the problem, can you supply any additional information about your setup or even a minimal reproducing example?

Thanks,
  Kevin

**Comment by iUwej** [comment] 2016-10-21 13:31
Hi @kwquick 
Thanks for the quick reply, I get the following error when working with the new fix.
`ERROR:root:Thespian Logger aborting (#0) with error
Traceback (most recent call last):
  File "/home/soko/Env/soko_env/local/lib/python2.7/site-packages/thespian-3.3.0-py2.7.egg/thespian/system/logdirector.py", line 75, in startupASLogger
    self._send_intent(TransmitIntent(self.myAddress, r))
NameError: global name 'self' is not defined
INFO:Thespian.Admin:ActorSystem Administrator startup @ ActorAddr-Q.ThespianQ
'Thespian__UpdateWork' object has no attribute 'message'
`
the startupASLogger is defined as a global function but use of self suggest it was meant to be  an instance method. I tried to redefine to be instance method  but this escalated to other issues(due to scoping, I guess).What's your take on this?

Thanks, iUwej

**Comment by kwquick** [comment] 2016-10-21 15:08
My apologies for being to hasty in the fix before.  Can you try updating that logdirector.py line 75 to read:

    transport.scheduleTransmit(TransmitIntent(transport.myAddress, r))

Let me know if that helps.  I'm not quite sure how this is getting triggered, so if you could tell me how you are using thespian with django I could investigate the interactions more.

**Comment by kwquick** [comment] 2016-11-08 05:31
Fixed in https://github.com/godaddy/Thespian/releases/tag/thespian-3.4.0

**Closed by kwquick** 2016-11-08 05:31 UTC
Labels: bug
